[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "ConwayGOL"
version = "0.0.1"
description = "Conway's Game of Life with extra events."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

dependencies = [
    "colorama"
]

[project.scripts]
terminal-video-player = "ConwayGOL.main:run"

[project.urls]
Homepage = "https://github.com/Stu67nt/ConwayGOL"

